### ISSUE TITLE
reduce scrolling in instructions.md

### ISSUE THREAD

**Issue by srearl** [EDIorg/taxonomyCleanr#18]
How about showing just a snippet of the long tables & output in `instructions.md`? As is, there is A LOT of scrolling in that otherwise nice and helpful page.

**Comment by clnsmth** [comment]
Thanks for this recommendation @srearl. 

[I've refactored the vignette](https://ediorg.github.io/taxonomyCleanr/articles/a_common_use_case.html) with `kableExtra::kable_styling` and `kableExtra::scroll_box` to confine large outputs to a scroll-able window. Additionally, I've migrated documentation to [a `pkgdown` built website](https://ediorg.github.io/taxonomyCleanr/index.html), which is the direction all EDI R packages are headed. The website definitely improves understanding and usability.

**Comment by srearl** [comment]
sooooo much better 😀
