### ISSUE TITLE
view_taxa_authorities() returns empty set

### ISSUE THREAD

**Issue by srearl** [EDIorg/taxonomyCleanr#19]
```r
view_taxa_authorities()
```

```r
# A tibble: 0 x 4
# … with 4 variables: id <int>, authority <chr>, resolve_sci_taxa <chr>, resolve_comm_taxa <chr>
```
Appears related to [complete.cases(gnr_list)](https://github.com/EDIorg/taxonomyCleanr/blob/3a5773bac2df721818eb2b0a2a47e9ac560661fb/R/view_taxa_authorities.R#L64)

**Comment by srearl** [comment]
looks like this was one of your tests....
```r
devtools::check()
```

```r
── 3. Failure: View available authorities (@test_view_taxa_authorities.R#10)  ──
class(authorities) not equal to "data.frame".
Lengths differ: 3 is not 1
```

**Comment by clnsmth** [comment]
Thanks for reporting this issue @srearl. Looks like `taxize` changed from data frames to tibbles. I'll get to work on refactoring `taxonomyCleanr`.

**Comment by srearl** [comment]
Thanks, @clnsmth. That could be. This error popped up when I was messing around in the package and running functions independently of the package (not quite sure how to describe that). If I load the package into a clean env., this works as expected.
