### ISSUE TITLE
resolve_comm_taxa() constrained to ITIS authority

### ISSUE THREAD

**Issue by srearl** [EDIorg/taxonomyCleanr#20]
```r
resolve_comm_taxa(path = my_path, data.sources = c(1,3))
```

```r
Error in resolve_comm_taxa(path = my_path, data.sources = c(1, 3)) : 
  Input argument "data.sources" contains unsupported data source IDs!
```

...same result if any authority other than `3` is selected.

Constraint seems to be occurring at the [input argument check](https://github.com/EDIorg/taxonomyCleanr/blob/3a5773bac2df721818eb2b0a2a47e9ac560661fb/R/resolve_comm_taxa.R#L64).

**Comment by clnsmth** [comment]
Thanks for reporting this issue @srearl. 

Currently ITIS is the only authority used by `taxonomyCleanr` for resolving common names. I've revised function documentation to clarify this along with an outdated vignette that suggested more authorities were supported for common searches. In general, the `view_taxa_authorities` function is the best place to find currently supported authorities for common and scientific name resolution.
