### ISSUE TITLE
replace_taxa() failing on quotes?

### ISSUE THREAD

**Issue by ctc3d** [EDIorg/taxonomyCleanr#34]
I've had a number of attempted replacements where this happened:
`> replace_taxa(path = map_path, input = "Tilia cordata 'Redmond'", output = 'Tilia cordata')`
`Error in replace_taxa(path = map_path, input = "Tilia cordata 'Redmond'",  : 
  "Tilia cordata 'Redmond'"does not match any taxa. Check your spelling.`

In fact it did match a lot of entries but no quotes-arrangement I came up with would convince the function to find them.

**Comment by clnsmth** [comment]
Thanks for reporting this issue @ctc3d. `utils::read.table()` is removing the quote characters. Using `readr::read_csv()` fixes the problem. I've implemented this change in the development branch and will merge with master upon the next release.
