### ISSUE TITLE
improve workflow for resolve_sci_taxa()

### ISSUE THREAD

**Issue by ctc3d** [EDIorg/taxonomyCleanr#35]
Two related issues:
We have a terrible internet connection here and I assume this problem is from that and not an ITIS problem, but I have gotten a lot of curl timeouts partway through `resolve_sci_taxa()`.  That wouldn't be a problem if the work-done state were saved somewhere but it's not -- so if the connection hangs on taxon 241 of 250 the function quits and has to be rerun from the beginning.  Each of these runs takes about fifteen minutes, so that's kind of a drag.  (I've gotten the same timeouts on `view_taxa_authorities()`, but that's obviously no big deal.)

More generally, `resolve_sci_taxa()` should pay more attention to what's already in taxa_map.csv.
Running `resolve_sci_taxa(path = map_path, data.sources = 3)` and then `resolve_sci_taxa(path = map_path, data.sources = 11)` redoes the entire resolution and rewrites the taxa map rather than checking just those entries with no taxa_clean.  That case probably isn't important, but if as I suggested earlier you resolve, then replace, then reresolve, it would be far more efficient to only query the entries that still lack their taxa_clean.

**Comment by clnsmth** [comment]
Thanks for these suggestions @ctc3d, they would make great enhancements!

FYI I'm wrapped up in other projects for the next month and will be spending little time on the taxonomyCleanr. As always, pull requests are welcome. I look forward to resuming work on this project.
