### ISSUE TITLE
resolve_sci_taxa() quits on connection problem

### ISSUE THREAD

**Issue by ctc3d** [EDIorg/taxonomyCleanr#37]
A more general version of my previous `resolve_sci_taxa()` issue: It should just be more resilient.  I tried to run `resolve_sci_taxa(path = map_path, data.sources = c(3,11))`.  Output was
`Searching ITIS for "Abies concolor"`
`Error: Not Found (HTTP 404)`
And there it died, without trying GBIF.  Reran it with only `data.sources = 11`; no problem.

Don't know why the 404 of course; ITIS has worked fine before, albeit slowly.

**Comment by clnsmth** [comment]
Agreed, resilience will be added.
