### ISSUE TITLE
connection problems with the authorities

### ISSUE THREAD

**Issue by ctc3d** [EDIorg/taxonomyCleanr#38]
I'm guessing this is not TCR's fault but I'm having recurring problems with connections to the authorities.  Right now ITIS is having a tendency to fail with a curl timeout error after 36 entries (and once after 72).  I tried changing the fatal entry and it made no difference.  GBIF seems okay today but yesterday was throwing a lot of http 503s.  Some part of this is likely related to our terrible DSL connection but since it's different problems for each it seems like something must be real on the other end.  I figure it's probably those servers, not TCR, but that 36-entry bit seems like it could be either.  Somehow...

**Comment by clnsmth** [comment]
Thanks for reporting this issue @ctc3d. I'll take a look.

**Comment by clnsmth** [comment]
Related to #16, #37
