### ISSUE TITLE
hiding make_taxonomic_coverage breaks EMLassemblyline?

### ISSUE THREAD

**Issue by RobLBaker** [EDIorg/taxonomyCleanr#49]
Hello!

I recently noticed that EMLassemblyline is no longer writing the taxonomicCoverage component to .xml when calling "make_eml()".  I have tested this on a couple of different datasets and temporalCoverage is successfully written, but taxonomicCoverage is not, despite the taxonomy_coverage.txt file successfully being generated.

I suspect the issue may trace back to changes made 2 weeks ago in taxonomyCleanr where makeTaxonomicCoverage() was set to internal only. EMLassemblyline's make_eml() function calls taxonomyCleanr::makeTaxonomicCoverage on line 896. 

This may not be the only issue, but it does appear to be one of the issues. I'm going to cross-post to EAL as well. Please excuse the extra post.

**Comment by clnsmth** [comment]
Thanks for reporting this @RobLBaker. I'll have a look.

**Comment by clnsmth** [comment]
@RobLBaker @juddpatterson, the fix is in. Please reinstall taxonomyCleanr and let me know if you hit any issues. Thanks again for reporting this!

Closed by c1118bbce83bcbc72eb3c5d5e5c604863fe1e0d0
